apiVersion: v1

kind: Service

metadata:
  name: devservice
  labels:
    servicelbl: labelname


spec:
  type: NodePort
  ports:
   - nodePort: 32005
     port: 9000
     targetPort: 80
  selector:
   type: dev
~             
