apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    env: prod
spec:
  containers:
    - name: firstcontainer
      image: coolgourav147/nginx-custom
      ports:
        - containerPort: 8080
      command: ["sh", "-c"]
      args:
        - echo "events {} http { server { listen 8080; location / { return 200 'Hello from container 1\n'; } } }" > /tmp/nginx.conf && nginx -g "daemon off;" -c /tmp/nginx.conf

    - name: secondcontainer
      image: coolgourav147/nginx-custom
      ports:
        - containerPort: 8081
      command: ["sh", "-c"]
      args:
        - echo "events {} http { server { listen 8081; location / { return 200 'Hello from container 2\n'; } } }" > /tmp/nginx.conf && nginx -g "daemon off;" -c /tmp/nginx.conf

