apiVersion: v1

kind: ReplicationController

metadata:
  name: firstrc
  labels:
     appname: fe

spec:
  replicas: 2
  template:
    metadata:
      name: myfirstpod
      labels:
        env: prod
        type: app

    spec:
      containers:
        - name: firstcontainer
          image: coolgourav147/nginx-custom

